name = "ethptc-services"
main = "src/index.ts"
compatibility_date = "2023-02-13"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bWRyZ2N3b3pwbHV6cWlwZGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzYxNTU4MTIsImV4cCI6MTk5MTczMTgxMn0.IJ405uDjq3Kg_xfC7yXVUUiMFI-iNxbsEhMURzFF4rI"
SUPABASE_URL = "https://dtmdrgcwozpluzqipdcg.supabase.co"