name = "ethptc-services"
main = "src/index.ts"
compatibility_date = "2023-02-13"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
SUPABASE_URL = "https://dtmdrgcwozpluzqipdcg.supabase.co"